//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "remotes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::sync_dirs::Entity")]
    SyncDirs,
}

impl Related<super::sync_dirs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SyncDirs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
