name: celeste
base: core22
grade: stable
confinement: strict
adopt-info: celeste
compression: lzo

package-repositories:
  - type: apt
    components: [jammy]
    suites: [prebuilt-mpr]
    key-id: B70EAE798718E0FE2972DD0C4FE9F2C43D9428A0
    url: https://proget.makedeb.org

parts:
  celeste:
    plugin: dump
    source: .
    parse-info: [ usr/share/metainfo/com.hunterwittenborn.Celeste.metainfo.xml ]
    build-packages:
      - rustup
      - just
      - libclang-15-dev
    build-snaps:
      - go
    override-build: |
      just build
      DESTDIR=$CRAFT_PART_INSTALL just install

  deps:
    after:
      - celeste
    plugin: nil
    stage-packages:
      - rclone
    prime:
      - usr/bin/rclone

slots:
  celeste:
    interface: dbus
    bus: session
    name: com.hunterwittenborn.Celeste
  celeste-app:
    interface: dbus
    bus: session
    name: com.hunterwittenborn.Celeste.App
  celeste-tray:
    interface: dbus
    bus: session
    name: com.hunterwittenborn.Celeste.Tray

apps:
  celeste:
    command: usr/bin/celeste
    autostart: com.hunterwittenborn.Celeste.desktop
    desktop: usr/share/applications/com.hunterwittenborn.Celeste.desktop
    extensions: [gnome]
    plugs:
      - gsettings
      - home
      - network
      - network-bind
      - unity7
    slots:
      - celeste
      - celeste-app
      - celeste-tray
