name: celeste
base: core22
grade: stable
confinement: strict
adopt-info: celeste
# TODO: Re-enable this once the Flatpak doesn't rely on the Snap for building.
#compression: lzo
architectures:
  - build-on: amd64
  - build-on: arm64


parts:
  rustup:
    plugin: nil
    build-packages: [wget]
    build-environment:
      - RUSTUP_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    override-pull: |
      wget https://sh.rustup.rs -O $CRAFT_PART_SRC/rustup-init.sh
      chmod +x $CRAFT_PART_SRC/rustup-init.sh
    override-build: |
      $CRAFT_PART_SRC/rustup-init.sh -y --no-modify-path
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      for i in `ls $RUSTUP_HOME/bin/`; do
        ln -s ../share/rust/bin/$i $CRAFT_PART_INSTALL/usr/bin/$i
      done
    override-prime: ''

  celeste:
    after: [ rustup ]
    plugin: dump
    source: .
    parse-info: [ "usr/share/metainfo/com.hunterwittenborn.Celeste.metainfo.xml" ]
    build-environment:
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
      - PATH: $RUSTUP_HOME/bin:$PATH
    build-packages:
      - libclang-15-dev
    build-snaps:
      - go
    override-build: |
      cargo install just
      just build
      DESTDIR=$CRAFT_PART_INSTALL just install

  deps:
    after:
      - celeste
    plugin: nil
    stage-packages:
      - rclone
    prime:
      - usr/bin/rclone

slots:
  celeste:
    interface: dbus
    bus: session
    name: com.hunterwittenborn.Celeste

apps:
  celeste:
    command: usr/bin/celeste
    autostart: com.hunterwittenborn.Celeste.desktop
    desktop: usr/share/applications/com.hunterwittenborn.Celeste.desktop
    extensions: [gnome]
    plugs:
      - gsettings
      - home
      - network
      - network-bind
      - unity7
    slots:
      - celeste
      - celeste-app
      - celeste-tray
